version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: moments_admin
      MONGO_INITDB_ROOT_PASSWORD: moments_admin
    volumes:
      - data:/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  moments-app:
    image: jjgouveia/moments-app:latest
    build: .
    container_name: moments-app
    ports:
      - "8080:8080"



volumes:
  data: { }

networks:
  default:
    name: mongodb_network
